### ISSUE TITLE
db_create error

### ISSUE THREAD

**Issue by gbprz** [IcarianComplex/LifeDocs#18]
When adding a new table for departments, I noticed that running the db_create script causes an error. 

I needed to comment out the following line to fix this, and then add it back in when I launched the application:
https://github.com/IcarianComplex/FireDB/blob/master/app/__init__.py#L26

It appears to me that when db is imported from app at the top of db_create, the error comes up since the form classes are attempting to pull from a table that doesn't exist yet. The line that triggers this is ```from app import db``` at the top of db_create.py. 

It seems to me like we'll need to separate the database initialization code I linked to above in __init__.py to avoid these errors in the future. Otherwise, people deploying the application for the first time will be loading forms that reference certain tables that don't exist yet, until they're initialized a few lines later. 

[Edit]
* This bug occurs on the adminInbox branch

**Comment by IcarianComplex** [comment]
fixed by 3fede674b661a6d2388faa30fc5a019acd7082e8
